#!/bin/bash

cd /home/pi/JuiceBox
echo "changed to JuiceBox"

while true; do
	if pgrep -x "python" > /dev/null
	then
		echo "working"
	else
		echo "starting new python script"
		python final.py
	fi

	sleep 5
done
