#!/bin/bash

cd /home/pi/JuiceBox
echo "changed to power tails"
python final.py
echo "closing powertails"

while true; do
	if pgrep -x "python" > /dev/null
	then
		echo "working"
	else
		echo "starting new python script"
		python final.py
	fi
done
