#!/bin/bash
source /home/pi/.token

# must first check if there is internet connection
python /home/pi/check_net.py


#cd /home/pi/clone
#now=$(date +'%h_%s_%m_%d_%y')
#echo $now

#mkdir -p $now
#mv power_tails $now

#cd /home/pi/clone
#git clone https://$TOKEN_TEMP@github.com/UTA-FabLab/power_tails
#cd /home/pi/clone/power_tails


#cd /home/pi/clone
# check if there is a directory called 
#if [ -e "power_tails/.git" ]; then
#	cd power_tails
#	git pull https://$TOKEN_TEMP@github.com/UTA-FabLab/power_tails
#else
#	echo "no powertails folder"
#	git clone https://$TOKEN_TEMP@github.com/UTA-FabLab/power_tails
#fi



python /home/clone/JuiceBox/final.py
