#!/bin/bash
#source /home/pi/.token

# must first check if there is internet connection



if [ -e "/home/pi/JuiceBox/.git" ]; then
	cd /home/pi/JuiceBox
#	git pull https://$TOKEN_TEMP@github.com/UTA-FabLab/power_tails
	git pull https://github.com/UTA-FabLab/JuiceBox
else
	cd /home/pi/
	echo "no JuiceBox folder"
#	git clone https://$TOKEN_TEMP@github.com/UTA-FabLab/power_tails
	git clone -b dev https://github.com/UTA-FabLab/JuiceBox
fi


chmod +x /home/pi/JuiceBox/JuiceBox_watchdog

./home/pi/JuiceBox/JuiceBox_watchdog
