#!/bin/bash
source /home/pi/.token

# must first check if there is internet connection
python /home/pi/JuiceBox/check_net.py


if [ -e "/home/pi/JuiceBox/.git" ]; then
	echo "pulling latest updates from github"
	cd /home/pi/JuiceBox
	git pull
else
	cd /home/pi/
	echo "no JuiceBox folder"
	git clone -b dev https://github.com/UTA-FabLab/JuiceBox
fi


chmod +x /home/pi/JuiceBox/JuiceBox_watchdog

/home/pi/JuiceBox/JuiceBox_watchdog
